import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Placeholder Firebase configuration.
///
/// Replace the dummy values with the real configuration generated by
/// `flutterfire configure` before shipping to production.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. Update firebase_options.dart.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'replace-with-your-web-api-key',
    appId: '1:000000000000:web:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'giftdrop-placeholder',
    authDomain: 'giftdrop-placeholder.firebaseapp.com',
    storageBucket: 'giftdrop-placeholder.appspot.com',
    measurementId: 'G-PLACEHOLDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3kxKttcHEu48bcDSGWTKPhV60Xbn7sQ',
    appId: '1:795629466965:android:0a2d8e38d2410546b16bdc',
    messagingSenderId: '795629466965',
    projectId: 'giftdrop-dc480',
    storageBucket: 'giftdrop-dc480.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'replace-with-your-ios-api-key',
    appId: '1:000000000000:ios:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'giftdrop-placeholder',
    storageBucket: 'giftdrop-placeholder.appspot.com',
    iosClientId: 'replace-with-your-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.giftdrop.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'replace-with-your-macos-api-key',
    appId: '1:000000000000:ios:placeholder-macos',
    messagingSenderId: '000000000000',
    projectId: 'giftdrop-placeholder',
    storageBucket: 'giftdrop-placeholder.appspot.com',
    iosClientId: 'replace-with-your-macos-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.giftdrop.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'replace-with-your-windows-api-key',
    appId: '1:000000000000:web:placeholder-windows',
    messagingSenderId: '000000000000',
    projectId: 'giftdrop-placeholder',
    storageBucket: 'giftdrop-placeholder.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'replace-with-your-linux-api-key',
    appId: '1:000000000000:web:placeholder-linux',
    messagingSenderId: '000000000000',
    projectId: 'giftdrop-placeholder',
    storageBucket: 'giftdrop-placeholder.appspot.com',
  );
}
